### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [winston3141/prj-rev-bwfs-dasmoto#5]
https://github.com/winston3141/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/index.css#L13-L32

There's a lot of repetition here. Use classes to group equivalent sections into groups, then use those class names as selectors so that you can easily apply the shared/common styles.

For example, if you'd given the `div` tags a class of `product`, you could rewrite a lot of this code into a single CSS rule, like so:

```css
.product {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
